version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DEBUG: 'True'  # Set DEBUG to 'False' in production
      DJANGO_SECRET_KEY: 'your-secret-key'
     

