# Generated by Django 4.2.3 on 2023-07-11 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='desc',
            field=models.CharField(default='Hello', max_length=255),
            preserve_default=False,
        ),
    ]
